# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0006_delete_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('logo', models.CharField(max_length=64)),
                ('logo_alt', models.CharField(max_length=32)),
                ('e_address', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=32)),
                ('period', models.CharField(max_length=32)),
            ],
        ),
    ]
