# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_day',
            field=models.CharField(max_length=32),
        ),
    ]
