# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('certif', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('logo', models.CharField(max_length=64)),
                ('logo_alt', models.CharField(max_length=32)),
                ('e_address', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='place_sturies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Studies'),
        ),
    ]
