# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20170124_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
