# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20170128_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='period',
        ),
        migrations.AddField(
            model_name='works',
            name='work_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='works',
            name='work_to',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
